In [ ]:
import numpy as np
import time
# 1. 파이썬 리스트를 사용한 경우
my_list = list(range(1_000_000))
start_time = time.time()
result_list = [x * 2for x in my_list]
end_time = time.time()
print(f"파이썬 리스트 실행 시간: {end_time - start_time:.5f}초")
# 2. 넘파이 배열을 사용한 경우
my_array = np.arange(1_000_000)
start_time = time.time()
result_array = my_array * 2
end_time = time.time()
print(f"넘파이 배열 실행 시간: {end_time - start_time:.5f}초")

파이썬 리스트 실행 시간: 0.07066초
넘파이 배열 실행 시간: 0.00236초

<>:6: SyntaxWarning: invalid decimal literal
<>:6: SyntaxWarning: invalid decimal literal
/tmp/ipython-input-1833742937.py:6: SyntaxWarning: invalid decimal literal
  result_list = [x * 2for x in my_list]

In [29]:
import pandas as pd

# 'your_file.csv'를 실제 CSV 파일 경로로 변경하세요.
df = pd.read_csv('iris_dataset_with_id.csv')

# 데이터프레임의 처음 5행을 출력하여 확인합니다.
display(df.tail(5))
minfive = df[df['sepal length (cm)']<5]
display(minfive)

,id,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
145,146,6.7,3.0,5.2,2.3,virginica
146,147,6.3,2.5,5.0,1.9,virginica
147,148,6.5,3.0,5.2,2.0,virginica
148,149,6.2,3.4,5.4,2.3,virginica
149,150,5.9,3.0,5.1,1.8,virginica

,id,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
1,2,4.9,3.0,1.4,0.2,setosa
2,3,4.7,3.2,1.3,0.2,setosa
3,4,4.6,3.1,1.5,0.2,setosa
6,7,4.6,3.4,1.4,0.3,setosa
8,9,4.4,2.9,1.4,0.2,setosa
9,10,4.9,3.1,1.5,0.1,setosa
11,12,4.8,3.4,1.6,0.2,setosa
12,13,4.8,3.0,1.4,0.1,setosa
13,14,4.3,3.0,1.1,0.1,setosa
22,23,4.6,3.6,1.0,0.2,setosa
24,25,4.8,3.4,1.9,0.2,setosa
29,30,4.7,3.2,1.6,0.2,setosa
30,31,4.8,3.1,1.6,0.2,setosa
34,35,4.9,3.1,1.5,0.2,setosa
37,38,4.9,3.6,1.4,0.1,setosa
38,39,4.4,3.0,1.3,0.2,setosa
41,42,4.5,2.3,1.3,0.3,setosa
42,43,4.4,3.2,1.3,0.2,setosa
45,46,4.8,3.0,1.4,0.3,setosa
47,48,4.6,3.2,1.4,0.2,setosa
57,58,4.9,2.4,3.3,1.0,versicolor
106,107,4.9,2.5,4.5,1.7,virginica